# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/feedster
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #            - run:
      #               name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #               command: sudo chmod +x ./gradle
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Sonarqube
#          command: ./gradlew sonarqube -Dsonar.projectKey=joniknegmatov_feedster -Dsonar.organization=joniknegmatov-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=36c580c5fd3af7a1b5ea25dcc77c0dcb73067694
      - run:
          name: Sonarqube
          command: ./gradlew createDebugCoverageReport jacocoTestReport sonarqube
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results